name: Release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: lts/gallium

      - run: npm ci && npm run build

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/swamp-camp-darwin-x64.zip,build/swamp-camp-win32-x64.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ matrix.os }}
