name: Release

on: push

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 16

            - run: npm i && npm run build

            - uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  artifacts: "build/swamp-camp-*.zip"
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ matrix.os }}
